// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjauciulrndxsbiqumkh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqYXVjaXVscm5keHNiaXF1bWtoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg5MjQwODksImV4cCI6MjA1NDUwMDA4OX0.HVma1CD9oZIVLFTtJEqeGWjcRMbuzVsGUI8YkOWv9m0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);